main: me.iBesty.Main
name: UltimateKits
version: 2.0
commands:
  sopa:
  kit:
  hitkill:
  togglepvp:
  skit:
  jellyfish:
  pvp:
  reset:
  kangaroo:
  rider:
  grandpa:
  report:
  anchor:
  snail:
  viper:
  critical:
  granadier:
  crash:
  darkmage:
  sniper:
  tp:
  fisherman:
  puurga:
  kitvip:
  pinguim:
  ninja:
  gorila:
  refiller:
  s:
  vis:
  invis:
  specialist:
  phantom:
  thor:
  tag:
  viking:
  stomper:
  endermage:
  fujao:
  grappler:
  tell:
  msg:
  build:
  ip:
  hulk:
  archer:
  gladiator:
  bc:
  broadcast:
  cchat:
  warps:
  fly:
  gm:
  head:
  inv:
  admin:
  tag:
  setspawn:
  spawn:
  setfps:
  fps:
  sethg:
  hg:
  setchallenge:
  challenge:
  setmdr:
  mdr:
  setrdm:
  rdm: